config/routes.rb
Rails.application.routes.draw do
  get "tweets/bottle"
  post "tweets/tweet_bottle"

  get "export/export"

  get "grapes/search"

  get "reports/cellar"
  get "reports/score_breakdown"
  get "reports/maturity_profile"
  get "reports/country"
  get "reports/yearly"
  get "reports/this_day_in_wine"
  get "reports/favourite_wines"
  get "reports/recent_good_bottles"

  get "wineries/search"
  get "wineries/show"

  get "home/index"

  resources :wines do
    resources :bottles
  end

  resources :bottles, :countries, :wineries

  root :to => "wines#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @title || "Wine Guide" %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-language" content="en">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Wine Guide</h1>
			</div>
		</div>
	    <nav class="navbar navbar-default" role="navigation">
		    <div class="navbar-header">
		    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      				<span class="sr-only">Toggle navigation</span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
      				<span class="icon-bar"></span>
    			</button>
				<%= link_to "Wines", wines_path, :class => 'navbar-brand' %>
		    </div>
		    <div class="collapse navbar-collapse navbar-ex1-collapse">
			    <ul class="nav navbar-nav">
					<li><%= link_to 'Create new wine', new_wine_path %></li>
				  	<li class="dropdown">
				  		<a class="dropdown-toggle" data-toggle="dropdown" href="#">Reports <b class="caret"></b></a>
				  		<ul class="dropdown-menu">
				  			<li><%= link_to "Cellar", { :controller => "reports", :action => "cellar" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "Country", { :controller => "reports", :action => "country" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "Yearly", { :controller => "reports", :action => "yearly" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "This Day in Wine", { :controller => "reports", :action => "this_day_in_wine" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "Favourite Wines", { :controller => "reports", :action => "favourite_wines" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "Recent Good Bottles", { :controller => "reports", :action => "recent_good_bottles" }, :class => 'cellar_report' %></li>
				  			<li><%= link_to "Score Breakdown", { :controller => "reports", :action => "score_breakdown" }, :class => 'cellar_report' %></li>
				  		</ul>
				  	</li>
			    </ul>
				<%= form_tag(wines_path, :method => "get", :class => 'navbar-form navbar-left', :role => 'search') do %>
					<div class="form-group">
			  			<%= text_field_tag 'term', nil, :placeholder => 'Winery, region', :length => '10' %>
					    <%= text_field_tag 'reviews_from', nil, :class => 'datepicker', :placeholder => 'Reviews from', :length => '10' %>
					    <%= text_field_tag 'reviews_to', nil, :class => 'datepicker', :placeholder => 'Reviews to', :length => '10' %>
			  		</div>
		  			<button type="submit" class="btn btn-default">Search</button>
			  	<% end %>
			  	<ul class="nav navbar-nav navbar-right">
				  	<li><%= link_to "Export", { :controller => 'export', :action => 'export' } %></li>
			  	</ul>
			</div>
	    </nav>
		<div class="row">
			<div class="col-md-12">
				<%= yield %>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		$('.datepicker').datepicker({
		    format: 'dd-mm-yyyy'
		});
	</script>
</body>
</html>